#  TUPLES ARE SIMILAR WITH LIST EXCEPT TUPLES CANNOT BE MODIFIED (THEY ARE IMMUTABLE)
#  TUPLE A(LSO PARENTHESIS INSTEAD OF SQUARE BRACKETS
numbers = (1, 3, 4)
print(numbers)
print(numbers.count(4))  #  THE COUNT METHOD IS USED TO COUNT ITEMS IN A TUPLE
print(numbers.index(4))  #   THE INDEX METHOD IS USED TO SHOW THE INDEX OF A VALUE IN A TUPLE


